# Generated by Django 5.0.3 on 2024-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTrendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('sma', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('signal_line', models.FloatField(blank=True, null=True)),
                ('upper_band', models.FloatField(blank=True, null=True)),
                ('lower_band', models.FloatField(blank=True, null=True)),
                ('fib_level1', models.FloatField(blank=True, null=True)),
                ('fib_level2', models.FloatField(blank=True, null=True)),
                ('fib_level3', models.FloatField(blank=True, null=True)),
                ('win_prob', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('win_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('sma', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('signal_line', models.FloatField(blank=True, null=True)),
                ('upper_band', models.FloatField(blank=True, null=True)),
                ('lower_band', models.FloatField(blank=True, null=True)),
                ('fib_level1', models.FloatField(blank=True, null=True)),
                ('fib_level2', models.FloatField(blank=True, null=True)),
                ('fib_level3', models.FloatField(blank=True, null=True)),
                ('trend_score', models.FloatField(blank=True, null=True)),
                ('win_prob', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('win_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('symbol', 'predicted_value')},
            },
        ),
    ]
