services:
  - name: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Trader.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "Trader.settings"
    # Add a setup command to run migrations before starting the server
    setupCommand: |
      python manage.py migrate --noinput